spring:
  application:
    name: warehouse-system

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

  flyway:
    enabled: true

  messages:
    encoding: UTF-8

  cache:
    type: caffeine
    cache-names: users
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size           